### ISSUE TITLE
 ditaa diagram not  render Chinese character correctly

### ISSUE THREAD

**Issue by 0000-bigtree** [asciidoctor/asciidoctor-diagram-java#1]
i use asciidoctor-diagram (1.3.0.preview.4) CRuby(2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]) with below ditaa code in a adoc(UTF-8)

```
ruby -Ku -S asciidoctor -r asciidoctor-diagram xxx.adoc
```
## [ditaa, "header", "png"]

+---------+
| 4 bytes | CRC
+---------+
| 1 byte  | 协议版本(Chinese Character!)
+---------+
| 2 bytes | 消息类型 ID(命令码)
## +---------+

produced png did not render Chinese character correctly.

![header](https://cloud.githubusercontent.com/assets/4982983/7549510/65dd0430-f66a-11e4-842e-c34878817bdd.png)

but i use 

```
java -Dfile.encoding=UTF-8 -jar ditaa0_9.jar(from sourceforge)  xxx.ditaa
```

produced png，it rendered fine.

![message_head_structure_4](https://cloud.githubusercontent.com/assets/4982983/7549514/8c334d9c-f66a-11e4-8e46-314efa170054.png)

**Comment by pepijnve** [comment]
Ditaa-mini is a fork of ditaa that strips away a bunch of unused and unfinished code in order to reduce the binary size. Source code is at https://github.com/pepijnve/ditaa. Beyond that it's identical to ditaa itself.

The issue tou're probably experiencing is one of character encoding where asciidoctor-diagram is passing the ditaa source code to ditaa using the wrong encoding.

Could you let me know which locale/character encoding your machine is configured for?

**Comment by pepijnve** [comment]
Also, in which encoding is your asciidoc file written? An example would be helpful.

**Comment by 0000-bigtree** [comment]
thanks for reply.

my Win7 system encoding is GBK, java system properties as below:

user.country=CN
user.language=zh
file.encoding=GBK

ruby Encoding.default_external as below:
irb(main):001:0> Encoding.default_external
=> #Encoding:GBK

 there are some example, files are both utf-8 encoding.

https://github.com/0000-bigtree/tmp/blob/master/example.adoc

https://github.com/0000-bigtree/tmp/blob/master/example.ditaa

again

```
ruby -Ku -S asciidoctor -r asciidoctor-diagram example.adoc
```

rendered error

```
java -Dfile.encoding=UTF-8 -jar ditaa0_9.jar(from sourceforge)  example.ditaa
```

rendered correctly

**Comment by pepijnve** [comment]
@0000-bigtree thanks for the extra information. That should be enough to reproduce this. I'm pretty sure the character encoding is getting mixed up somewhere along the processing path. Should be easy enough to pinpoint and fix.

**Comment by pepijnve** [comment]
Replaced by https://github.com/asciidoctor/asciidoctor-diagram/issues/73
