### ISSUE TITLE
Themes are not applied to Structurizr diagrams

### ISSUE THREAD

**Issue by timw** [asciidoctor/asciidoctor-diagram-java#13]
Structurizr supports theming via the `theme` and `themes` directives in the Structurizr DSL [1] (as well as supporting inline styles).
e.g. 

```
    views {
   ...
        themes default "https://static.structurizr.com/themes/microsoft-azure-2021.01.26/theme.json"
    }
```

When these are processed with the Structurizr CLI, the styles in themes are rendered correctly.
When the same diagram is processed using asciidoctor-diagram, the styles contained in themes are not applied, although inline styles are.

Inspecting the Structurizr CLI code, it can be seen that `ThemeUtils.loadThemes(Workspace)` [2] is invoked when the `ExportCommand` is run [3].  To quote the `ThemeUtils` docs:  _"This implementation simply copies the styles from all themes into the workspace."_

I suspect that simply including a `ThemeUtils.loadThemes` invocation on the `Workspace` after it is parsed in the Structurizr DiagramGenerator [4] would fix this.

I've attached [structurizr-theme-test.zip](https://github.com/asciidoctor/asciidoctor-diagram-java/files/11743895/structurizr-theme-test.zip) which contains a test Asciidoc document and script that will generate and compare the images generated by asciidoctor-diagram and structurizr-cli using the `plantuml`, `plantuml-c4` and `graphviz` renderers in a single document.
(This works on a Mac using graphviz and structurizr-cli from Homebrew, but should adapt easily to other installations).
The workspace here is just a copy of one of the Strucuturizr samples, and there's nothing special about it apart from it contains enough elements to style, and that it references themes (in this case 2, but even just using the `default` theme will illustrate the issue).

[1]: https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#theme
[2]: https://github.com/structurizr/java/blob/master/structurizr-client/src/com/structurizr/view/ThemeUtils.java#LL69C29-L69C29
[3]: https://github.com/structurizr/cli/blob/master/src/main/java/com/structurizr/cli/export/ExportCommand.java#L141
[4]: https://github.com/asciidoctor/asciidoctor-diagram-java/blob/master/structurizr/src/main/java/org/asciidoctor/diagram/structurizr/Structurizr.java#L87

**Comment by pepijnve** [comment]
Thanks for trying out the functionality already. As you've noticed it's still early days. I made this for my own work, but haven't gotten 'round to actually using this yet.

Your suggestion seems correct indeed. It's a bit unfortunate that we have to duplicate that logic, but the CLI codebase wasn't really made to be called externally.

**Comment by pepijnve** [comment]
Should be fixed in https://github.com/asciidoctor/asciidoctor-diagram/commit/6652e1394d511067612f47d3d9b9a5b5520504d2

**Comment by timw** [comment]
Thanks for the fix @pepijnve  - yeah, I figured it was a work in progress so happy to help move it along.
My overall goal is to get it workable in the IntelliJ plugin for technical documentation - with the fix for https://github.com/asciidoctor/asciidoctor-diagram/issues/415 and this one, I think it's almost there.

The only other thing that would make things easier is a non-ENV method for locating the Structurizr installation (that's awkward to achieve with a Java IDE plugin). I think an attribute would be the way to go since the IDE plugin can wire those (it does so for `graphvizdot` now among other attributes).

**Comment by pepijnve** [comment]
The Java runtime is initialised (either in process for JRuby or a single 'daemon' sub process for MRI) only once before document processing actually begins. At that point I don't have access to the document yet so document attributes won't work.
For JRuby specifically I could add an alternative that uses Java system properties though. Would that be work?

**Comment by timw** [comment]
System properties would definitely be easier for Java IDE scenarios - they tend to be built in Java themselves, so getting to the JVM launcher config is easier than modifying environment, so that'd be a usable option.
e.g. JetBrains Toolbox makes it easy to modify the JVM options for the IDE, so the IntelliJ plugin will work well with that approach.

**Comment by ahus1** [comment]
I remember that for other diagram types the executable could be specified using an attribute.  As JVM parameters are global and not document/project specific. They are also generally available in AsciiDoc and not bound to Java. WDYT?

**Comment by ahus1** [comment]
Oh, reading the previous comment, they don't work as described above. Nevermind...
