### ISSUE TITLE
structurizr add workspace.json usage

### ISSUE THREAD

**Issue by mathisloge** [asciidoctor/asciidoctor-diagram-java#16]
If one uses https://github.com/structurizr/lite to manually place the elements in the views, than those informations are stored in a workspace.json.

structurizr-cli allows the usage of the generated workspace.json or the workspace.dsl

The workspace.json contains all informations of the workspace.dsl.

If I would currently doing `structurizr::workspace.json[view="MyView", renderer="plantuml-c4", format="svg"]` it would just error out, since the dsl is expected.

It would be quite good if I could just pass the json instead of the dsl file.

Further links

https://docs.structurizr.com/cli/export#examples
https://github.com/structurizr/json

https://github.com/structurizr/cli/blob/master/src/main/java/com/structurizr/cli/AbstractCommand.java#L50-L102

**Comment by pepijnve** [comment]
Integrated in https://github.com/asciidoctor/asciidoctor-diagram/commit/08cf0fc09e21da706a48f2b5d67dd724511aadef

**Comment by mathisloge** [comment]
Thank you 💥
