### ISSUE TITLE
plantuml.jar for 1.2020.26 damaged

### ISSUE THREAD

**Issue by anderscore-hjhessmann** [asciidoctor/asciidoctor-diagram-java#6]
The plantuml.jar in your repository does not work on Windows. There is a fixed plantuml-jar-asl-1.2020.26.zip available on http://sourceforge.net/projects/plantuml/files/plantuml-jar-asl-1.2020.26.zip/download.

I hope there will be soon a new release of asciidoctorj-diagram that support this version of plantuml.

**Comment by pepijnve** [comment]
This will be fixed as part of https://github.com/asciidoctor/asciidoctor-diagram/issues/312

**Comment by btd2ek** [comment]
I tried to create a PNG image from  MathML but I got the Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/events/CustomEvent
Is there something I did wrong?
The issue seems to be coming from MathML.java, line 158
JEuclidView view = JEuclidView(node, ctx, graphics).
