### ISSUE TITLE
Update plantuml version

### ISSUE THREAD

**Issue by zeldigas** [asciidoctor/asciidoctor-diagram-java#8]
Plantuml released a lot of new versions with fixes and enhancements: https://plantuml.com/en/changes, https://mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml/1.2022.2

How about updating this module with latest version as well?

**Comment by pepijnve** [comment]
There's not much point. The PlantUML version embedded here is only used for compilation purposes. I should probably replace it with a gradle dependency instead.
