### ISSUE TITLE
Exception, NoClassDefFoundError org/w3c/dom/events/CustomEvent

### ISSUE THREAD

**Issue by btd2ek** [asciidoctor/asciidoctor-diagram-java#9]
Please how do I resolve this issue
I tried to create a PNG image from MathML but I got the Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/events/CustomEvent
Is there something I did wrong?
The issue seems to be coming from MathML.java, line 158
JEuclidView view = JEuclidView(node, ctx, graphics).

**Comment by pepijnve** [comment]
No idea what's wrong here but looks similar to https://sourceforge.net/p/jeuclid/bugs/44/
